package:
  name: mingw-runtime
  version: 4.7

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - mingw # [win]
